export { default as WorkspacePage } from './workspace/workspace';
export { default as DashboardPage } from './dashboard/dashboard-new';
export { WorkflowPage } from './workflow/workflow';
export { WorkflowsPage } from './workflows/workflows';
export { JobPage } from './job/job-page';
export { JobsPage } from './jobs/jobs';
export { UserInfoPage } from './userinfo/userinfo';
export { SearchPage } from './search/search';
export { ComponentPage } from './components/component-page';
export { ComponentsPage } from './components/components-page';
export { Page403Forbidden } from './400/page-403-forbidden';
export { Page404NotFound } from './400/page-404-not-found';
export { AdminPage } from './admin/admin';
