name: prod

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  deploy:
    name: Update deployment
    runs-on: ubuntu-latest
    env:
      EMAIL: ${{ github.event.head_commit.author.email }}
      NAME: ${{ github.event.head_commit.author.name }}
    steps:
      - name: Checkout infra
        uses: actions/checkout@v2
        with:
          ref: main
          repository: equinor/flowify-infrastructure
          ssh-key: ${{ secrets.FLOWIFY_INFRA_DEPLOY_KEY }}
      - name: Update infra
        run: |
          SHA_SHORT=$(echo ${{ github.sha }} | cut -c1-7)
          SHA_LONG=${{ github.sha }}
          git config --global user.email "${EMAIL}"
          git config --global user.name  "GitHub Actions (${NAME})"
          sed -i "s/newTag:.*/newTag: \"$SHA_SHORT\"/g" kube/frontend/overlays/prod/kustomization.yaml
          git add kube/frontend/overlays/prod/kustomization.yaml
          git commit --message "GHA: Update production imageTag" || true
          git push
